apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep01bishal
  labels:
    app: httpd
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: bishaldhimal/bishalnginximg
  selector:
    matchLabels:
      app: httpd
